@startuml

interface Engine
interface Arguments
interface ScriptValidator
interface ScriptService
class JsCtrl

Arguments <.l. Engine
Engine <.. ScriptService
Engine <.l. JsCtrl
ScriptService <.l. ScriptValidator

@enduml