@startuml

[系统管理] -- [权限系统]
[系统管理] -- [参数设置]
[权限系统] -- [菜单配置]
[权限系统] -- [组织架构]
[权限系统] -- [用户管理]
[组织架构] -- [岗位职称]
[组织架构] -- [权限定义]

[人力资源] -- [档案管理]
[档案管理] -- [招聘管理]
[招聘管理] -- [社会招聘]
[招聘管理] -- [校园招聘]
[档案管理] -- [入职管理]
[档案管理] -- [离职管理]
[人力资源] -- [出差管理]
[人力资源] -- [假期管理]
[假期管理] -- [公共假期]
[假期管理] -- [请假流程]
[假期管理] -- [请假管理]
[人力资源] -- [人员晋升]

@enduml