@startuml

actor 业务需求

package 组件化{
[组件1]
[组件2]
[组件N]
}

package 定制化{
[定制1]
[定制2]
[定制N]
}

cloud {
node 解决方案1
node 解决方案2
node 解决方案N
}

业务需求 --> 组件化
业务需求 --> 定制化

组件化 --> 解决方案1
组件化 --> 解决方案2
组件化 --> 解决方案N

定制化 --> 解决方案1
定制化 --> 解决方案2
定制化 --> 解决方案N

@enduml