@startuml

package Tephra {
[core] <-- [dao]
[dao] <-- [ctrl]
[ctrl] <-- [ctrl-http]
[ctrl] <-- [ctrl-socket]
[ctrl] <-- [script]
[ctrl] <-- [weixin]
[ctrl] <-- [carousel]
[ctrl] <-- [hadoop]
[script] <-- [web]
[ctrl-http] <-- [web]

[core-test] <-l- [core]
[dao-test] <-l- [dao]
[core-test] <-- [dao-test]
[ctrl-test] <-l- [ctrl]
[dao-test] <-- [ctrl-test]
[ctrl-test] <-- [test]
}

@enduml